baseURL = "https://piercepurselley.github.io/"
title = "Pierce Purselley"
languageCode = "en-us"

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Writer and Comedian in Los Angeles. Mortified Los Angeles Showrunner."
  bio = "Writer and Comedian in Los Angeles.<br><br><a href=\"https://getmortified.com/\" target=\"_blank\" rel=\"noopener noreferrer\">Mortified Los Angeles</a> Showrunner."
